version: '3.8'

services:
  cockpit:
    image: cockpit/ws:latest
    container_name: cockpit
    ports:
      - "9090:9090"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/host
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    restart: unless-stopped